---
title: "Project 2 : Data Wrangling"
author: Heidi, Harriet, Viola 
output: 
  html_document:
    cold_folding: hide
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r, message= FALSE}
# Loading datasets ----
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```


```{r, message= FALSE, echo= FALSE}
# Loading libraries ----
library(tidyverse)
library(dplyr)
library(ggrepel)
library(RColorBrewer)
library(gridExtra)
```

```{r, message= FALSE, eval=FALSE}
# Verification of the data ----
glimpse(house_elections)
glimpse(candidates)
glimpse(committees)
glimpse(contributions)
```

```{r,message= FALSE}
# Modifying the candidates data frame ----
candidates_NY2012 <- candidates %>%
  filter(cand_office_state == "NY")%>%
  filter(cand_party_affiliation == "DEM")%>%
  filter(cand_election_yr == 2012) %>%
  select(cand_id, 
         cand_name)
```

```{r,message= FALSE}
# Creating a table of candidate IDs from the wrangled candidates data set ----
cand_IDs <- select(candidates_NY2012,
                   matches("cand_id"))
```

```{r,message= FALSE}
# Wrangling the contributions data frame ----
contributions_NY <- contributions %>% 
  filter(cand_id %in% cand_IDs$cand_id) %>%
  select(cand_id, 
         transaction_amt)
```

```{r,message= FALSE}
# Wrangling the house elections data frame ----
house_elections_NY2012 <- house_elections %>%
  select(fec_id, 
         ge_winner, 
         incumbent)
```

```{r,message= FALSE}
# Joining the wrangled contributions and candidates data frames using full_join ----
contr_cand_joined <- full_join(contributions_NY,
                               candidates_NY2012, 
                               by= "cand_id") %>%
  group_by(cand_id, 
           cand_name) %>%
  summarise(sum = sum(transaction_amt)) %>%
  arrange(sum)
```

```{r,message= FALSE}
# Wrangling house elections by filtering with candidates IDs in the joined candidate and contribution data frame ----
house_elections_NY2012 <- filter(house_elections_NY2012,
                                 fec_id %in% contr_cand_joined$cand_id) %>%
  mutate(cand_id = fec_id)
```

```{r,message= FALSE}
# Creating the final data frame by using inner join to join the wrangled house election and the previously joined data frame of candidates and contributions ----
final_df <- inner_join(contr_cand_joined,
                       house_elections_NY2012, 
                       by = "cand_id") %>%
  select(cand_name, 
         sum, 
         ge_winner, 
         incumbent) %>%
  arrange(sum) %>%
  filter(sum >= 40000) %>% # we chose to filter out candidates who received less than 50 000 dollars 
  filter(!is.na(sum))
```
#Creating the data graphic using the final data frame



```{r,message= FALSE}
options(scipen = 100000)
my_plot1 <- ggplot(data = final_df, 
                   aes(x = reorder(cand_name,-sum), 
                       y = sum, fill = ge_winner)) + 
  geom_bar(position = "dodge",
           stat = "identity") +
  coord_flip() +
  ggtitle("Does contribution amount influence house election success?") +
  xlab("") +
  labs(fill="") +
  scale_fill_discrete(labels=c("Lost", "Won")) +
  scale_y_continuous(name = "Money Spent (millions of USD)",                breaks=c(0,2000000,4000000),
                     labels=c("0$", 
                              "2,000,000$",
                              "4,000,000$")) + 
  theme(axis.text.x = element_text(angle = 0))+
  scale_fill_manual(values=c("#95A5A6","#00CC00"))
```

```{r}
incumbent <- c("Non incumbent", "Incumbent")
names(incumbent)<-c("FALSE","TRUE")
```

```{r}
# Faceting the final data graphic by incumbent ----
my_plot2 <- ggplot(data = final_df, 
                   aes(x = reorder(cand_name,-sum),
                       y = sum, 
                       fill = ge_winner)) + 
  geom_bar(position = "dodge",
           stat = "identity")+
  coord_flip() +
  ggtitle("Does contribution amount influence house election success?") +
  xlab("") +
  labs(fill="") +
  scale_fill_discrete(labels = c("Lost","Won")) +
  scale_y_continuous(
    name = "Money Spent (millions of USD)",
    breaks=c(0,2000000,4000000),
    labels=c("0$", "2,000,000$", "4,000,000$")) +
 scale_fill_manual(values=c("#95A5A6","#00CC00"))+
  facet_wrap(~incumbent,labeller = labeller(incumbent = incumbent))+
   theme_get()
```

```{r}
# The plot ----
my_plot1  
```

```{r}
# Second plot faceted by incumbents ----
my_plot2
```


# Functions

Creating a function to wrangle candidates data
```{r,message= FALSE}
# Function 1 generalizes the data wrangling for the candidates dataset ----
function1_candidates <- function(year, state) {
  candidates %>%
    filter(cand_election_yr == year) %>%
    filter(cand_party_affiliation == party) %>%
    filter(cand_office_state == state) %>%
    select(cand_id, cand_name) 
}
```

```{r,message= FALSE}
# Function 2 takes the data frame made by the 1st function and creates a list of the candidate IDs from that data frame ----
function2_candid_id <- function(function1df) {
  select(function1df, matches("cand_id"))
}
```

```{r,message= FALSE}
# Function 3 takes the data frame made from function 2 and uses it to wrangle the contributions data frame ----
function3_contributions <- function(function2df) {
  contributions %>%
    filter(cand_id %in%
             function2df$cand_id) %>%
    select(cand_id, transaction_amt)
}
```

```{r,message= FALSE}
# Function 4 takes the wrangled candidates data frame produced by function 1 and the wrangled contribution data frame produced by function 3 and joins those two dataframes ----
function4_joincand_cont <- function(function1df, function3df) {
  full_join(function1df, function3df, by="cand_id") %>%
    group_by(cand_id, cand_name) %>%
    summarise(sum=sum(transaction_amt)) %>%
    arrange(sum)
}
```

```{r,message= FALSE}
# Function 5 takes the data frame created by function 4, and uses it to wrangle the house elections data frame ----
function5_house_elec <- function(function4df) {
  house_elections %>% 
    select(fec_id, ge_winner, incumbent) %>%
    filter(fec_id %in% function4df$cand_id) %>%
    mutate(cand_id = fec_id)
}

```

```{r,message= FALSE}
# Function 6 takes the data frame created by function 4 and function 5 and joins them to create the final data frame that will produce the overall analysis
function6_finaldf <- function(function4df, function5df) {
  inner_join(function4df, function5df, by = "cand_id") %>%
    select(cand_name, sum, ge_winner, incumbent) %>%
    arrange(ge_winner) %>%
    filter(!is.na(sum)) %>%
    filter(sum > 50000)
}
```


```{r,message= FALSE}
NYR <- function1_candidates(2012, "TX")
```

```{r}
function7_plot <- function(function6df) {
	  ggplot(data = function6df, 
	                   aes(x = reorder(cand_name,-sum), 
	                       y = sum, 
	                       fill = ge_winner)) + 
	  geom_bar(position = "dodge",
	           stat = "identity") +
	                     coord_flip() +
  ggtitle("Does contribution amount influence house election success?") +
  xlab("") +
  labs(fill="") +
  scale_fill_discrete(labels=c("Lost", "Won")) +
  scale_y_continuous(name = "Money Spent (millions of USD)",                breaks=c(0,2000000,4000000),
                     labels=c("0$", 
                              "2,000,000$",
                              "4,000,000$")) + 
  theme(axis.text.x = element_text(angle = 0))+
  scale_fill_manual(values=c("#95A5A6","#00CC00"))
}
```

```{r}
function(function7plotname) {
  function7plotname + facet_wrap(~incumbent,labeller = labeller(incumbent = incumbent))+
   theme_get()
}
```

```{r,message= FALSE}
NYR <- function1_candidates(2012, "NY", "REP")
NYRcandid <- function2_candid_id(NYR)
NYRcontr <- function3_contributions(NYRcandid)
NYRjoined <- function4_joincand_cont(NYR, NYRcontr)
NYRhouse <- function5_house_elec(NYRjoined)
NYRfinal <- function6_finaldf(NYRjoined, NYRhouse)

```


```{r}
NYRplot <- function7_plot(NYRfinal)
NYRplot2 <- function8_facet(NYRplot)
```

```{r}
NYRplot
NYRplot2
```

```{r}
devtools::install_github("benmarwick/wordcountaddin", type = "source", dependencies = TRUE)
```


```{r}
wordcountaddin::word_count("Project2.Rmd")
```


#Using a GitHub repository and including a link to it in the footnotes
We used Github Repository ^[https://github.com/violanguyen/sds192-mp2.git] 




